
### LINODE ENV = https://burger-api.amirazmi.dev
### GET ALL BURGERS
GET https://burger-api.amirazmi.dev/burgers

### DELETE ALL BURGERS
DELETE https://burger-api.amirazmi.dev/burgers HTTP/1.1

### CREATE BURGER
POST https://burger-api.amirazmi.dev/burgers HTTP/1.1
Content-Type: application/json

{
  "name": "daging",
  "description": "Burger daging sedap dengan sekeping daging.",
  "keywords": []
}

### UPDATE BURGER
PUT https://burger-api.amirazmi.dev/burgers/65435702136236a8c9e468a5 HTTP/1.1
Content-Type: application/json

{
  "keywords": ["daging", "meat"]
}